# Generated by Django 5.2 on 2025-05-24 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_departement', models.CharField(max_length=120, unique=True)),
                ('departement_code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('middle_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('mobile_number', models.CharField(max_length=30)),
                ('employement_type', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('CT', 'contract'), ('Fx', 'Filexble')], max_length=23)),
                ('start_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('departements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.departement')),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='departement_head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_departement', to='users.employementdetails'),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_skill', models.CharField(max_length=36)),
                ('descriptions', models.TextField()),
                ('location_of_skill_get', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], max_length=45)),
                ('department', models.ManyToManyField(max_length=30, to='users.departement')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficions', models.CharField(choices=[('Advanced', 'advanced'), ('middle_level', 'middle_level'), ('Beginer', 'Beginer')], max_length=200)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employementdetails')),
                ('skill_optaian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.skills')),
            ],
        ),
    ]
