# Generated by Django 5.2 on 2025-05-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_departement_employementdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employementdetails',
            name='employement_type',
            field=models.CharField(choices=[('full_time', 'Full-Time'), ('par_time', 'Part-Time'), ('contract', 'contract'), ('filexble', 'Filexble')], max_length=23),
        ),
        migrations.AlterField(
            model_name='employementdetails',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10),
        ),
    ]
