# Generated by Django 5.2 on 2025-05-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_employementdetails_employement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employementdetails',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
