# Generated by Django 5.2 on 2025-05-26 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employementdetails_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employementdetails',
            name='deleted_at',
        ),
    ]
