# Generated by Django 5.2 on 2025-05-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_employementdetails_isdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='Isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
